# Generated by Django 6.0 on 2026-04-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='order',
            name='Mobile_no',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='mobile_no',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
