# Generated by Django 6.0 on 2026-04-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_image_url_order_mobile_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mobile_no',
            new_name='Mobile_no',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
